### ISSUE TITLE
Bæta inn tékki á virðisaukaskattsnúmeri

### ISSUE THREAD

**Issue by markusgud** [stadlar/IST-FUT-GRV#5]
Í eldri skematronu fyrir TS136 er að finna reglu sem tékkar á VSK númeri ef virðisaukaskattur er notaður á reikningi. Æskilegt væri að þessi regla væri inni.

Reglan eins og hún stendur:
`<axsl:when test="(number(cac:TaxTotal/cbc:TaxAmount) = 0) or ((string-length(string(cac:AccountingSupplierParty/cac:Party/cac:PartyTaxScheme/cbc:CompanyID)) &gt;= 5) and (string-length(string(cac:AccountingSupplierParty/cac:Party/cac:PartyTaxScheme/cbc:CompanyID)) &lt;= 8))"/>`

Textanum sem er skilað:
`<svrl:text>[ISNAT-T10-R017]-Ef reiknaður er VSK á reikningi skal VSK númer seljanda að koma fram og vera 5 eða 6 stafir (7 eða 8 stafir er einnig leyft komi landakóði á undan sbr. IS12345).</svrl:text>`

**Comment by stadlar** [comment]
TN-GRV-190628 - Umræða um afgreiðslu
- Opna umræðu við hagsmunaaðila - GV sendir ábendingu til TN-GRV 
- Ákveðið að fresta útgáfu þar til VH hefur leyst á sama hátt og t.d. ítalir m.v. 7 eða 8 stafi með IS kóðanum sett inn og IG sendir á VH og tekinn verður símafundur ef þykir þurfa annars er releasað. 
- IG býr til branch og býr til CEN reviewer.
- VH sem útfærir regluna - IG, MG, GB, DB
- GB bendir á að við höfum ekki forritunarútfærsluna fyrir þessa reglu
- GB bendir á að Peppol hefur gefið út breytingar á skematronu og quick fix næsta útgáfa Peppol er í nóvember

-
