### ISSUE TITLE
Reglur um útgáfudag

### ISSUE THREAD

**Issue by midran** [stadlar/IST-FUT-GRV#6]
Sælir félagar, 
Það kemur reglulega fyrir að við erum að fá reikninga sem eru allt of gamlir.  Nánast alltaf er ástæðan mistök sendanda. 

Tillaga okkar til að bæta gæði reikninga er því að : 
-	EF reikningur er dagsettur (issue date) meira en 100 daga afturvirkt skal HAFNA honum.  
-	Miðum við móttökudag.

Spurning hvort þið sjáið einhverja vankanta á þessari nálgun.  Ég hef rætt þetta aðeins við bókhaldsfólk og endurskoðendur hjá okkur og þeir sjá ekki meinbug á þessari leið. 
kveðja
 
Bergþór Skúlason, sérfræðingur 
Fjársýsla ríkisins 
Vegmúla 3, 108 Reykjavík 
Sími / Tel: (+354) 545 7500 
www.fjs.is - Fyrirvari/Disclaimer

**Comment by midran** [comment]
Til að vera samhæfðir við Peppol þá þyrfti þessi regla, ef samþykkt, að vera skilyrt. "EF land seljanda = IS ÞÁ ...", annars gæti hún fellt gilda erlenda Peppol reikninga.

**Comment by IngibergurUnimaze** [comment]
Það hefur verið ákveðið að samþykkja ekki þessa reglu og því verður þessu lokað
